Added the toolbar feature to the project as well as the headline page
Tchilo/My-portfolio-for--mobile pull request #1
Opened 2021-06-08 15:53 UTC by Tchilo

Added the toolbar feature to the project 
Added the headline page to the project 
Added a screenshot of the project

2021-06-08 18:34 UTC, jubaan requested changes
Hi @Tchilo , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-08 18:34 UTC, jubaan commented on style.css
> +  .headline-page h1 {
- [ ] BAD `.headline-page h1` Good `.main-title`

2021-06-08 18:34 UTC, jubaan commented on style.css
> +  .headline-page h2 {
- [ ] BAD `.headline-page h2` Good `.subtitle`

2021-06-08 18:34 UTC, jubaan commented on style.css
> +  .headline-page p {
- [ ] BAD `.headline-page p` Good `.headline-content`

2021-06-08 20:03 UTC, Temmarie commented on index.html
> +    </section>
- [ ] You must stick to the design as much as possible (e.g., font, colours, images, tests, margins) using the templates in [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). Look out for the following :
- The fonts,
- The toolbar/navigation bar 
- The Image sizes and placement.
_See the images below for comparisons_

**Original** | **Your clone**
  ----------- | -----------
 ![image](https://user-images.githubusercontent.com/49621279/121249300-48906800-c859-11eb-86e0-639b044760e5.png) | ![image](https://user-images.githubusercontent.com/49621279/121249630-a4f38780-c859-11eb-864f-bedc41eba23d.png)

2021-06-09 11:35 UTC, DeliceLydia commented on index.html
> +    </section>
- [ ] According to the requirements you need to stick to the design as much as possible(fonts, colors, etc)
![tmp](https://user-images.githubusercontent.com/44745855/121347266-472d7100-c927-11eb-93c3-9cb8b4218b1e.png)

If you can compare your portfolio and the design it's really different, that is why I encourage you to work on it again and don't give up take this as learning!

2021-06-09 11:39 UTC, DeliceLydia requested changes
## Hi @Tchilo , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._


### Keep Your Head Up High!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

N.B: Because this review was the third as described in the requirements you are required to start the project again! and please don't give up!
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-09 13:34 UTC, vichuge approved these changes
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi @Tchilo , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121364073-12a4bf80-c8fd-11eb-9558-51171661798d.gif)


## Optional suggestions to improve your project 🥇 

Please, consider:
- [OPTIONAL] Use [Color Cop](http://colorcop.net/download/) to take the exactly hexadecimal code to each color, in that way your CSS style could improve this.
- [OPTIONAL] [Google fonts](https://fonts.google.com/) is another tool could help you to get a better typography

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-09 16:10 UTC, merged